/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteServicesIndexRouteImport } from './routes/_site.services.index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesIndexRoute = SiteServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/services/': typeof SiteServicesIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/': typeof SiteIndexRoute
  '/services': typeof SiteServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/services/': typeof SiteServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/about' | '/contact' | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/about' | '/contact' | '/' | '/services'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/'
    | '/_site/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/': {
      id: '/_site/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof SiteServicesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteServicesIndexRoute: typeof SiteServicesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteServicesIndexRoute: SiteServicesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
